PlaceObj("XTemplate", {
  __is_kind_of = "PDACommonButtonClass",
  group = "Zulu PDA",
  id = "PDACommonButtonOrange",
  PlaceObj("XTemplateWindow", {
    "__class",
    "PDACommonButtonClass",
    "LayoutMethod",
    "Box",
    "Background",
    RGBA(215, 159, 80, 255),
    "FocusedBackground",
    RGBA(215, 159, 80, 255),
    "DisabledBackground",
    RGBA(255, 255, 255, 255),
    "RolloverBackground",
    RGBA(215, 159, 80, 255),
    "PressedBackground",
    RGBA(215, 159, 80, 255),
    "Image",
    "UI/PDA/os_system_buttons",
    "FrameBox",
    box(10, 10, 10, 10),
    "TextStyle",
    "PDACommonButton",
    "Translate",
    true,
    "ColumnsUse",
    "abcca"
  })
})
