PlaceObj("XTemplate", {
  __is_kind_of = "PDASatelliteAIMMercClass",
  group = "Zulu Satellite UI",
  id = "PDASatelliteMercAIM",
  PlaceObj("XTemplateWindow", {
    "__class",
    "PDASatelliteAIMMercClass",
    "MinWidth",
    125,
    "MinHeight",
    190,
    "MaxWidth",
    125,
    "MaxHeight",
    190,
    "LayoutMethod",
    "VList",
    "UseClipBox",
    false,
    "BorderColor",
    RGBA(255, 255, 255, 0),
    "Background",
    RGBA(255, 255, 255, 0),
    "MouseCursor",
    "UI/Cursors/Pda_Hand.tga",
    "ChildrenHandleMouse",
    true,
    "FocusedBorderColor",
    RGBA(255, 255, 255, 0),
    "FocusedBackground",
    RGBA(255, 255, 255, 0),
    "DisabledBorderColor",
    RGBA(255, 255, 255, 0),
    "RolloverBackground",
    RGBA(255, 255, 255, 0),
    "PressedBackground",
    RGBA(255, 255, 255, 0)
  }, {
    PlaceObj("XTemplateWindow", {
      "__class",
      "XTextWithStyleBasedOnSize",
      "Id",
      "idPrice",
      "Dock",
      "bottom",
      "HAlign",
      "center",
      "VAlign",
      "bottom",
      "TextStyle",
      "PDAMercPrice",
      "Translate",
      true,
      "TextStyleSmall",
      "PDAMercPrice_Small"
    }),
    PlaceObj("XTemplateWindow", {
      "Id",
      "idContent",
      "Margins",
      box(2, 28, 2, 0),
      "Dock",
      "box",
      "Background",
      RGBA(230, 222, 203, 255),
      "BackgroundRectGlowSize",
      1,
      "BackgroundRectGlowColor",
      RGBA(230, 222, 203, 255)
    }, {
      PlaceObj("XTemplateWindow", {
        "__class",
        "XFrame",
        "Id",
        "idSelectedRounding",
        "Dock",
        "box",
        "Image",
        "UI/PDA/os_portrait_selection",
        "FrameBox",
        box(5, 5, 5, 5)
      }),
      PlaceObj("XTemplateWindow", {
        "__class",
        "XImage",
        "Id",
        "idPortraitBG",
        "IdNode",
        false,
        "Margins",
        box(5, 5, 5, 0),
        "Image",
        "UI/Hud/portrait_background",
        "ImageFit",
        "stretch"
      }, {
        PlaceObj("XTemplateWindow", {
          "__class",
          "XImage",
          "UIEffectModifierId",
          "Default",
          "Id",
          "idPortrait",
          "IdNode",
          false,
          "ZOrder",
          2,
          "Margins",
          box(0, -20, 0, 0),
          "ImageFit",
          "height",
          "ImageRect",
          box(36, 0, 264, 246)
        }),
        PlaceObj("XTemplateWindow", {
          "__class",
          "XSquareWindow",
          "Id",
          "idExpensive",
          "ZOrder",
          3,
          "HAlign",
          "left",
          "VAlign",
          "bottom",
          "MinWidth",
          28,
          "MinHeight",
          28,
          "MaxWidth",
          28,
          "MaxHeight",
          28,
          "Visible",
          false,
          "Background",
          RGBA(191, 67, 77, 255)
        }, {
          PlaceObj("XTemplateWindow", {
            "__class",
            "XText",
            "HAlign",
            "center",
            "VAlign",
            "center",
            "Clip",
            false,
            "UseClipBox",
            false,
            "HandleMouse",
            false,
            "ChildrenHandleMouse",
            false,
            "TextStyle",
            "MercTooExpensive",
            "Translate",
            true,
            "Text",
            T(474052898772, "$"),
            "TextVAlign",
            "center"
          })
        }),
        PlaceObj("XTemplateWindow", {
          "__class",
          "XSquareWindow",
          "RolloverTemplate",
          "RolloverGeneric",
          "RolloverAnchor",
          "right",
          "RolloverOffset",
          box(10, 0, 0, 0),
          "Id",
          "idClassIconBg",
          "ZOrder",
          3,
          "HAlign",
          "right",
          "VAlign",
          "bottom",
          "MinWidth",
          28,
          "MinHeight",
          28,
          "MaxWidth",
          28,
          "MaxHeight",
          28,
          "HandleMouse",
          true
        }, {
          PlaceObj("XTemplateWindow", {
            "__class",
            "XImage",
            "Id",
            "idClassIcon",
            "HAlign",
            "center",
            "VAlign",
            "center",
            "MinWidth",
            20,
            "MinHeight",
            20,
            "MaxWidth",
            20,
            "MaxHeight",
            20,
            "ImageFit",
            "stretch",
            "ImageColor",
            RGBA(27, 31, 45, 255)
          }),
          PlaceObj("XTemplateFunc", {
            "comment",
            "XButton is weird about propagating clicks from within it",
            "name",
            "OnMouseButtonDown(self, pos, button)",
            "func",
            function(self, pos, button)
              local node = self:ResolveId("node")
              return node:OnPress()
            end
          })
        }),
        PlaceObj("XTemplateTemplate", {
          "__template",
          "MercContractWarningIcon",
          "OnPress",
          function(self, gamepad)
          end
        }),
        PlaceObj("XTemplateWindow", {
          "__class",
          "XText",
          "Id",
          "idOffline",
          "HAlign",
          "center",
          "VAlign",
          "center",
          "Clip",
          false,
          "UseClipBox",
          false,
          "DrawOnTop",
          true,
          "HandleMouse",
          false,
          "ChildrenHandleMouse",
          false,
          "TextStyle",
          "DescriptionTextRed",
          "Translate",
          true,
          "Text",
          T(746980318390, "OFFLINE"),
          "TextHAlign",
          "center",
          "TextVAlign",
          "center"
        })
      }),
      PlaceObj("XTemplateWindow", {
        "Id",
        "idBottomSection",
        "Margins",
        box(5, 0, 5, 0),
        "Dock",
        "bottom",
        "MinHeight",
        30,
        "MaxHeight",
        30,
        "LayoutMethod",
        "HList"
      }, {
        PlaceObj("XTemplateWindow", {
          "__class",
          "XImage",
          "Id",
          "idOnlineStatusIcon",
          "Margins",
          box(4, 0, 0, 0),
          "HAlign",
          "left",
          "VAlign",
          "center",
          "UseClipBox",
          false,
          "FoldWhenHidden",
          true,
          "Image",
          "UI/PDA/snype_on",
          "ImageScale",
          point(800, 800)
        }),
        PlaceObj("XTemplateWindow", {
          "__class",
          "XText",
          "Id",
          "idName",
          "Margins",
          box(2, 0, 0, 0),
          "HAlign",
          "left",
          "VAlign",
          "center",
          "Clip",
          false,
          "UseClipBox",
          false,
          "HandleMouse",
          false,
          "ChildrenHandleMouse",
          false,
          "TextStyle",
          "PDAMercNameCard_Light",
          "Translate",
          true,
          "Text",
          T(168293618443, "<Nick>"),
          "TextVAlign",
          "bottom"
        })
      })
    })
  })
})
