OptionsData.VideoPresetsData = {
  Low = {
    Textures = "Low",
    Shadows = "Low",
    Terrain = "Low",
    Effects = "Low",
    ViewDistance = "Low",
    Antialiasing = "FXAA",
    Anisotropy = "Off",
    ResolutionPercent = "67",
    Lights = "Low",
    Postprocess = "Low",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "Low",
    MaxFps = "240",
    SSAO = "Off",
    SSR = "Off"
  },
  Medium = {
    Textures = "Medium",
    Shadows = "Medium",
    Terrain = "Medium",
    Effects = "Medium",
    ViewDistance = "Medium",
    Antialiasing = "FXAA",
    Anisotropy = "2x",
    ResolutionPercent = "100",
    Lights = "Medium",
    Postprocess = "Medium",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "Medium",
    MaxFps = "240",
    SSAO = "On",
    SSR = "Medium"
  },
  High = {
    Textures = "High",
    Shadows = "High",
    Terrain = "High",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "SMAA",
    Anisotropy = "4x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "High",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "High",
    MaxFps = "240",
    SSAO = "On",
    SSR = "High"
  },
  Ultra = {
    Textures = "Ultra",
    Shadows = "Ultra",
    Terrain = "Ultra",
    Effects = "Ultra",
    ViewDistance = "Ultra",
    Antialiasing = "SMAA",
    Anisotropy = "16x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "Ultra",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "High",
    MaxFps = "240",
    SSAO = "On",
    SSR = "Ultra"
  },
  XboxOne = {
    Textures = "Medium (Consoles)",
    Shadows = "Medium (PS4,XboxOne)",
    Terrain = "Medium",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "FXAA",
    Anisotropy = "4x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "Low",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    FPSCounter = "Off",
    ObjectDetail = "Low",
    SSAO = "Off",
    SSR = "Off"
  },
  XboxOneX = {
    Textures = "Medium (Consoles)",
    Shadows = "High",
    Terrain = "Medium",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "FXAA",
    Anisotropy = "8x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "Low",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    FPSCounter = "Off",
    SSAO = "On",
    SSR = "High"
  },
  XboxSeries = {
    Textures = "High",
    Shadows = "High",
    Terrain = "High",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "FXAA",
    Anisotropy = "8x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "Medium",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    FPSCounter = "Off",
    SSAO = "On",
    SSR = "High"
  },
  XboxSeriesX = {
    Textures = "Ultra",
    Shadows = "High",
    Terrain = "Ultra",
    Effects = "Ultra",
    ViewDistance = "Ultra",
    Antialiasing = "SMAA",
    Anisotropy = "16x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "High",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "High",
    FPSCounter = "Off",
    SSAO = "On",
    SSR = "High"
  },
  PS4 = {
    Textures = "Medium (Consoles)",
    Shadows = "Medium (PS4,XboxOne)",
    Terrain = "Medium",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "FXAA",
    Anisotropy = "4x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "Medium",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "Low",
    FPSCounter = "Off",
    SSAO = "Off",
    SSR = "Off"
  },
  PS4Pro = {
    Textures = "Medium (Consoles)",
    Shadows = "High (PS4Pro)",
    Terrain = "Medium",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "FXAA",
    Anisotropy = "8x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "Medium",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "Low",
    FPSCounter = "Off",
    SSAO = "On",
    SSR = "High"
  },
  PS5 = {
    Textures = "Ultra",
    Shadows = "High",
    Terrain = "Ultra",
    Effects = "Ultra",
    ViewDistance = "Ultra",
    Antialiasing = "SMAA",
    Anisotropy = "16x",
    ResolutionPercent = "100",
    Lights = "High",
    Postprocess = "High",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "High",
    FPSCounter = "Off",
    SSAO = "On",
    SSR = "High"
  },
  Switch = {
    Textures = "Low",
    Shadows = "Low (Switch)",
    Terrain = "Low",
    Effects = "Low (Switch)",
    ViewDistance = "Low (Switch)",
    ObjectDetail = "Very Low",
    Antialiasing = "FXAA",
    Anisotropy = "2x",
    ResolutionPercent = "switch",
    Lights = "Low",
    Postprocess = "Low",
    Bloom = "Off",
    EyeAdaptation = "On",
    Vignette = "Off",
    FPSCounter = "Off",
    MaxFps = "Unlimited",
    SSAO = "Off",
    SSR = "Off"
  },
  SteamDeck = {
    Textures = "High",
    Shadows = "Medium",
    Terrain = "High",
    Effects = "High",
    ViewDistance = "High",
    Antialiasing = "FSR2",
    Anisotropy = "2x",
    ResolutionPercent = "77",
    Lights = "High",
    Postprocess = "High",
    Bloom = "On",
    EyeAdaptation = "On",
    Vignette = "On",
    ObjectDetail = "Medium",
    MaxFps = "30",
    SSAO = "On",
    SSR = "Medium",
    Vsync = true
  }
}
local ExcludeFromPresetCheck = {Vsync = true, FPSCounter = true}
if FirstLoad then
  PresetVideoOptions = {}
  for preset, vals in pairs(OptionsData.VideoPresetsData) do
    for k, _ in pairs(vals) do
      if not ExcludeFromPresetCheck[k] then
        PresetVideoOptions[k] = true
      end
    end
  end
end
OptionsData.Options.ObjectDetail = {
  {
    value = "Low",
    text = T(215633457448, "Low"),
    ObjectLODPercents = 50,
    Optionals = 50,
    EyeCandies = 33,
    hr = {
      ObjectLODCapMin = 1,
      LightShadowsDetailLevel = 1,
      LightShadowsMinContribDistance = 40
    }
  },
  {
    value = "Medium",
    text = T(679289081998, "Medium"),
    ObjectLODPercents = 75,
    Optionals = 75,
    EyeCandies = 66,
    hr = {
      ObjectLODCapMin = 0,
      LightShadowsDetailLevel = 2,
      LightShadowsMinContribDistance = 60
    }
  },
  {
    value = "High",
    text = T(564085803851, "High"),
    ObjectLODPercents = 100,
    Optionals = 100,
    EyeCandies = 100,
    hr = {
      ObjectLODCapMin = 0,
      LightShadowsDetailLevel = 3,
      LightShadowsMinContribDistance = 100
    }
  }
}
