UndefineClass("TheBeast")
DefineClass.TheBeast = {
  __parents = {"UnitData"},
  __generated_by_class = "UnitDataCompositeDef",
  object_class = "UnitData",
  Health = 93,
  Agility = 95,
  Dexterity = 96,
  Strength = 87,
  Wisdom = 84,
  Leadership = 70,
  Marksmanship = 96,
  Mechanical = 69,
  Explosives = 74,
  Medical = 65,
  Portrait = "UI/NPCsPortraits/TheBeast",
  BigPortrait = "UI/NPCs/TheBeast",
  Name = T(122342069727, "The Beast"),
  Randomization = true,
  Affiliation = "Other",
  StartingLevel = 8,
  ImportantNPC = true,
  neutral_retaliate = true,
  AIKeywords = {"Flank"},
  archetype = "Skirmisher",
  role = "Recon",
  CanManEmplacements = false,
  AlwaysUseOpeningAttack = true,
  PinnedDownChance = 100,
  MaxAttacks = 2,
  RewardExperience = 0,
  MaxHitPoints = 60,
  StartingPerks = {
    "AutoWeapons",
    "Loner",
    "Hotblood",
    "CQCTraining",
    "Shatterhand"
  },
  AppearancesList = {
    PlaceObj("AppearanceWeight", {"Preset", "TheBeast"})
  },
  Equipment = {"TheBeast"},
  pollyvoice = "Kendra",
  gender = "Female",
  PersistentSessionId = "NPC_TheBeast"
}
