UndefineClass("TheMajor")
DefineClass.TheMajor = {
  __parents = {"UnitData"},
  __generated_by_class = "UnitDataCompositeDef",
  object_class = "UnitData",
  Health = 82,
  Agility = 88,
  Dexterity = 91,
  Strength = 86,
  Wisdom = 85,
  Leadership = 85,
  Marksmanship = 92,
  Mechanical = 62,
  Explosives = 45,
  Medical = 11,
  Portrait = "UI/MercsPortraits/unknown",
  BigPortrait = "UI/Mercs/Spike",
  Name = T(261450464980, "The Major"),
  Affiliation = "Legion",
  StartingLevel = 8,
  ImportantNPC = true,
  villain = true,
  neutral_retaliate = true,
  archetype = "TheMajor",
  role = "Commander",
  CanManEmplacements = false,
  MaxAttacks = 2,
  DefeatBehavior = "Defeated",
  RetreatBehavior = "None",
  StartingPerks = {
    "AutoWeapons",
    "BulletHell",
    "Hobbler",
    "LeadFromTheFront",
    "OpportunisticKiller",
    "Counterfire",
    "Killzone",
    "SwiftStrike",
    "LightningReaction",
    "Ironclad"
  },
  AppearancesList = {
    PlaceObj("AppearanceWeight", {"Preset", "TheMajor"})
  },
  Equipment = {"TheMajor"},
  Tier = "Legendary",
  gender = "Male",
  PersistentSessionId = "NPC_TheMajor",
  VoiceResponseId = "Spike"
}
