const.SlabGroundOffset = -50
const.SlabNoMaterial = "none"
const.SlabSize = point(const.SlabSizeX, const.SlabSizeY, const.SlabSizeZ)
const.SlabBox = box(-(const.SlabSizeX / 2), -(const.SlabSizeY / 2), 0, const.SlabSizeX / 2, const.SlabSizeY / 2, const.SlabSizeZ)
const.SlabOffset = point(const.SlabOffsetX, const.SlabOffsetY, 0)
const.SlabMaterialProps = {}
const.DebrisFadeAwayTime = 30000
const.DebrisDisappearTime = 5000
const.DebrisExplodeDeviationAngle = 3600
const.DebrisExplodeSlabDelay = 200
const.DebrisExplodeRadius = 2500
