PlaceObj("XTemplate", {
  __is_kind_of = "XTextButton",
  group = "Editor",
  id = "EditorToolbarButton",
  save_in = "Common",
  PlaceObj("XTemplateWindow", {
    "__class",
    "XTextButton",
    "RolloverTranslate",
    false,
    "RolloverTemplate",
    "XEditorToolbarRollover",
    "RolloverAnchor",
    "bottom",
    "BorderWidth",
    2,
    "MaxWidth",
    30,
    "MaxHeight",
    30,
    "BorderColor",
    RGBA(0, 0, 0, 0),
    "Background",
    RGBA(0, 0, 0, 0),
    "RolloverBackground",
    RGBA(40, 163, 255, 128),
    "RolloverBorderColor",
    RGBA(38, 146, 227, 255),
    "PressedBackground",
    RGBA(40, 163, 255, 140),
    "PressedBorderColor",
    RGBA(38, 146, 227, 255),
    "Image",
    "CommonAssets/UI/round-frame-20.tga",
    "ImageScale",
    point(500, 500),
    "FrameBox",
    box(9, 9, 9, 9)
  })
})
