PlaceObj("XTemplate", {
  __is_kind_of = "XToggleButton",
  group = "Editor",
  id = "EditorToolbarToggleButton",
  save_in = "Common",
  PlaceObj("XTemplateWindow", {
    "__class",
    "XToggleButton",
    "RolloverTranslate",
    false,
    "RolloverTemplate",
    "XEditorToolbarRollover",
    "RolloverAnchor",
    "bottom",
    "BorderWidth",
    2,
    "MaxWidth",
    30,
    "MaxHeight",
    30,
    "BorderColor",
    RGBA(0, 0, 0, 0),
    "Background",
    RGBA(0, 0, 0, 0),
    "RolloverBackground",
    RGBA(204, 232, 255, 255),
    "RolloverBorderColor",
    RGBA(38, 146, 227, 255),
    "PressedBackground",
    RGBA(121, 189, 241, 255),
    "PressedBorderColor",
    RGBA(38, 146, 227, 255),
    "Image",
    "CommonAssets/UI/round-frame-20.tga",
    "ImageScale",
    point(500, 500),
    "FrameBox",
    box(9, 9, 9, 9),
    "ToggledBackground",
    RGBA(35, 87, 191, 255)
  })
})
