PlaceObj("XTemplate", {
  __is_kind_of = "XToolBar",
  group = "GedControls",
  id = "GedToolBar",
  save_in = "Ged",
  PlaceObj("XTemplateWindow", {
    "__class",
    "XToolBar",
    "RolloverTemplate",
    "XRolloverWindow",
    "RolloverAnchor",
    "bottom",
    "Id",
    "idToolbar",
    "Margins",
    box(0, 1, 0, 1),
    "Padding",
    box(1, 1, 1, 1),
    "Dock",
    "top",
    "Toolbar",
    "main",
    "Show",
    "icon",
    "ButtonTemplate",
    "GedToolbarButton",
    "ToggleButtonTemplate",
    "GedToolbarToggleButton"
  })
})
